parameters:
    pim_enrich.mass_edit.temporary_file.cleaner.class: Pim\Bundle\EnrichBundle\MassEditAction\Cleaner\MassEditTemporaryFileCleaner
    pim_enrich.mass_edit.add_to_variant.cleaner.class: Pim\Bundle\EnrichBundle\MassEditAction\Cleaner\MassEditVariantGroupCleaner

services:
    pim_enrich.mass_edit.temporary_file.cleaner:
        class: %pim_enrich.mass_edit.temporary_file.cleaner.class%
        arguments:
            - '@pim_catalog.updater.product'
            - '@pim_validator'
            - '@pim_catalog.repository.product_mass_action'
            - '@pim_catalog.repository.attribute'

    pim_enrich.mass_edit.add_to_variant.cleaner:
        class: %pim_enrich.mass_edit.add_to_variant.cleaner.class%
        arguments:
            - '@pim_catalog.query.product_query_builder_factory'
            - '@pim_enrich.product.paginator'
            - '@akeneo_storage_utils.doctrine.object_detacher'
            - '@pim_enrich.repository.mass_edit'
            - '@pim_catalog.object_manager.product'
            - '@pim_catalog.repository.group'
